// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Je33/imperial_fleet/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// SpaceshipRepository is an autogenerated mock type for the SpaceshipRepository type
type SpaceshipRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *SpaceshipRepository) Create(_a0 context.Context, _a1 *domain.Spaceship) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Spaceship) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *SpaceshipRepository) Delete(_a0 context.Context, _a1 *domain.Spaceship) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Spaceship) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: _a0
func (_m *SpaceshipRepository) GetAll(_a0 context.Context) ([]*domain.Spaceship, error) {
	ret := _m.Called(_a0)

	var r0 []*domain.Spaceship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Spaceship, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Spaceship); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Spaceship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: _a0, _a1
func (_m *SpaceshipRepository) GetById(_a0 context.Context, _a1 uint) (*domain.Spaceship, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *domain.Spaceship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Spaceship, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Spaceship); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Spaceship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *SpaceshipRepository) Update(_a0 context.Context, _a1 *domain.Spaceship) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Spaceship) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSpaceshipRepository creates a new instance of SpaceshipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpaceshipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpaceshipRepository {
	mock := &SpaceshipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
